import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { useLocation } from "wouter";
import {
  ArrowLeft, ArrowRight, Check, ChevronDown, Compass, Flag, Globe2,
  Home as HomeIcon, Link2, Loader2, LogOut, Menu, MessageCircle,
  Pencil, Plus, Search, Send, Settings2, ShieldAlert, ShieldCheck,
  UserRound, X, Zap,
} from "lucide-react";

type Screen = "landing" | "dashboard" | "discover" | "connections" | "profile" | "chat" | "member";
type SignalMode = "need" | "can";

const logoSrc = "/official-nivo-logo.png";
const heroImage = "/manus-storage/nivo-hero-field_7ca54bc2.png";
const categories = ["All", "Business", "Technology", "Design", "Education", "Jobs", "Services", "Advice", "Collaboration", "Personal", "Other"];
const blankProfile = { country: "", languages: "", about: "", skills: "", interests: "", photoUrl: "" };
const blankSignal = { title: "", description: "", category: "Technology", language: "English", location: "" };

function OfficialLogo({ small = false }: { small?: boolean }) {
  return <div className={`official-logo ${small ? "official-logo--small" : ""}`}><img src={logoSrc} alt="NIVO official logo" onError={(event) => { event.currentTarget.style.display = "none"; }} /><span className="logo-fallback">NIVO</span></div>;
}

function Avatar({ name, photoUrl, large = false }: { name: string | null | undefined; photoUrl?: string | null; large?: boolean }) {
  const initials = (name ?? "N").split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  return <div className={`avatar ${large ? "avatar--large" : ""}`}>{photoUrl ? <img src={photoUrl} alt="" /> : initials}</div>;
}

function parseList(value: string | null | undefined) {
  try { const parsed = JSON.parse(value ?? "[]"); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; }
}

function InputLabel({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="form-label"><span>{label}</span>{children}</label>;
}

export default function Home() {
  const auth = useAuth();
  const utils = trpc.useUtils();
  const [location, navigate] = useLocation();
  const routeChatId = Number(location.match(/^\/chat\/(\d+)$/)?.[1]) || null;
  const routeMemberId = Number(location.match(/^\/members\/(\d+)$/)?.[1]) || null;
  const screen: Screen = location === "/discover" ? "discover" : location === "/connections" ? "connections" : location === "/profile" ? "profile" : routeChatId ? "chat" : routeMemberId ? "member" : auth.isAuthenticated ? "dashboard" : "landing";
  const [menuOpen, setMenuOpen] = useState(false);
  const [typeFilter, setTypeFilter] = useState<"all" | SignalMode>("all");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [composerMode, setComposerMode] = useState<SignalMode | null>(null);
  const [signalForm, setSignalForm] = useState(blankSignal);
  const [requestSignalId, setRequestSignalId] = useState<number | null>(null);
  const [requestNote, setRequestNote] = useState("");
  const [messageBody, setMessageBody] = useState("");
  const [profileForm, setProfileForm] = useState(blankProfile);

  const filters = useMemo(() => ({ type: typeFilter === "all" ? undefined : typeFilter, category: categoryFilter === "All" ? undefined : categoryFilter }), [typeFilter, categoryFilter]);
  const signalsQuery = trpc.signals.list.useQuery(filters, { refetchOnWindowFocus: false });
  const profileQuery = trpc.profile.me.useQuery(undefined, { enabled: auth.isAuthenticated, refetchOnWindowFocus: false });
  const ownSignalsQuery = trpc.signals.mine.useQuery(undefined, { enabled: auth.isAuthenticated, refetchOnWindowFocus: false });
  const connectionsQuery = trpc.connections.list.useQuery(undefined, { enabled: auth.isAuthenticated, refetchOnWindowFocus: false });
  const messagesQuery = trpc.messages.list.useQuery({ id: routeChatId ?? 0 }, { enabled: auth.isAuthenticated && Boolean(routeChatId), refetchOnWindowFocus: false });
  const memberQuery = trpc.profile.get.useQuery({ userId: routeMemberId ?? 0 }, { enabled: Boolean(routeMemberId), refetchOnWindowFocus: false });

  const signals = signalsQuery.data ?? [];
  const connections = connectionsQuery.data ?? [];
  const selectedSignal = signals.find((signal) => signal.id === requestSignalId) ?? null;
  const selectedConnection = connections.find((connection) => connection.id === routeChatId) ?? null;

  useEffect(() => {
    const privateScreen = screen === "dashboard" || screen === "connections" || screen === "profile" || screen === "chat";
    if (privateScreen && !auth.loading && !auth.isAuthenticated) startLogin();
  }, [auth.isAuthenticated, auth.loading, screen]);

  useEffect(() => {
    const profile = profileQuery.data?.profile;
    if (!profile) return;
    setProfileForm({
      country: profile.country ?? "",
      languages: parseList(profile.languages).join(", "),
      about: profile.about ?? "",
      skills: parseList(profile.skills).join(", "),
      interests: parseList(profile.interests).join(", "),
      photoUrl: profile.photoUrl ?? "",
    });
  }, [profileQuery.data]);

  const notifyError = (error: unknown) => toast.error(error instanceof Error ? error.message : "Something went wrong. Please try again.");
  const createSignal = trpc.signals.create.useMutation({ onSuccess: async () => { await Promise.all([utils.signals.list.invalidate(), utils.signals.mine.invalidate()]); setComposerMode(null); setSignalForm(blankSignal); navigate("/"); toast.success("Your signal is live."); }, onError: notifyError });
  const saveProfile = trpc.profile.update.useMutation({ onSuccess: async () => { await utils.profile.me.invalidate(); toast.success("Profile saved."); }, onError: notifyError });
  const requestConnection = trpc.connections.request.useMutation({ onSuccess: async () => { await utils.connections.list.invalidate(); setRequestSignalId(null); setRequestNote(""); toast.success("Connection request sent."); }, onError: notifyError });
  const acceptConnection = trpc.connections.accept.useMutation({ onSuccess: async () => { await utils.connections.list.invalidate(); toast.success("Connection accepted. You can now message each other."); }, onError: notifyError });
  const declineConnection = trpc.connections.decline.useMutation({ onSuccess: async () => { await utils.connections.list.invalidate(); toast("Connection request declined."); }, onError: notifyError });
  const cancelConnection = trpc.connections.cancel.useMutation({ onSuccess: async () => { await utils.connections.list.invalidate(); toast("Connection request cancelled."); }, onError: notifyError });
  const sendMessage = trpc.messages.send.useMutation({ onSuccess: async () => { setMessageBody(""); await Promise.all([utils.messages.list.invalidate(), utils.connections.list.invalidate()]); }, onError: notifyError });
  const blockUser = trpc.trust.block.useMutation({ onSuccess: async () => { await Promise.all([utils.signals.list.invalidate(), utils.connections.list.invalidate()]); setRequestSignalId(null); toast.success("Profile blocked. You will no longer see each other’s signals or connections."); }, onError: notifyError });
  const reportUser = trpc.trust.report.useMutation({ onSuccess: () => toast.success("Report received. Thank you for helping keep NIVO safe."), onError: notifyError });

  const requireAuth = (next: () => void) => auth.isAuthenticated ? next() : startLogin();
  const go = (next: Screen, id?: number) => {
    const requiresAuthentication = next === "dashboard" || next === "connections" || next === "profile" || next === "chat";
    if (requiresAuthentication && !auth.isAuthenticated) {
      startLogin();
      return;
    }
    const route = next === "discover" ? "/discover" : next === "connections" ? "/connections" : next === "profile" ? "/profile" : next === "chat" && id ? `/chat/${id}` : next === "member" && id ? `/members/${id}` : "/";
    navigate(route);
    setMenuOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
  const startComposer = (mode: SignalMode) => requireAuth(() => { setComposerMode(mode); setSignalForm(blankSignal); });
  const submitSignal = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!composerMode) return; createSignal.mutate({ ...signalForm, type: composerMode, location: signalForm.location.trim() || null }); };
  const openConnection = (signalId: number) => requireAuth(() => { const signal = signals.find((item) => item.id === signalId); if (!signal) return; if (signal.owner.id === auth.user?.id) return toast.error("This is your own signal."); setRequestSignalId(signalId); setRequestNote(`I believe I can help with “${signal.title}”.`); });
  const submitConnection = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedSignal) return; requestConnection.mutate({ recipientId: selectedSignal.owner.id, signalId: selectedSignal.id, note: requestNote }); };
  const submitProfile = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const list = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean); saveProfile.mutate({ country: profileForm.country.trim() || null, languages: list(profileForm.languages), about: profileForm.about.trim() || null, skills: list(profileForm.skills), interests: list(profileForm.interests), photoUrl: profileForm.photoUrl.trim() || null }); };
  const submitMessage = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!routeChatId || !messageBody.trim()) return; sendMessage.mutate({ connectionId: routeChatId, body: messageBody.trim() }); };

  if (screen === "landing" && !auth.isAuthenticated) {
    return <div className="nivo-app"><header className="topbar"><button className="brand brand-button" onClick={() => go("landing")}><OfficialLogo /><span className="brand-name">NIVO</span></button><nav className="desktop-nav"><button onClick={() => go("discover")}>Explore</button><button onClick={() => document.getElementById("how")?.scrollIntoView({ behavior: "smooth" })}>How it works</button></nav><div className="topbar-actions"><button className="login-btn" onClick={startLogin}>Log in</button><button className="primary-btn primary-btn--compact" onClick={startLogin}>Get started <ArrowRight size={15} /></button><button className="menu-btn" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="mobile-menu"><button onClick={() => go("discover")}>Explore signals</button><button onClick={startLogin}>Log in</button></div>}</header><main><section className="hero hero--functional"><div className="hero-image" style={{ backgroundImage: `url(${heroImage})` }} /><div className="hero-copy"><p className="eyebrow eyebrow--bright"><span className="live-pulse" /> A human matching network</p><h1>What do you <em>need?</em><br />What can you <em>offer?</em></h1><p className="hero-lede">Share a real need or capability. Discover people. Start a useful conversation.</p><div className="hero-actions"><button className="primary-btn" onClick={startLogin}>Create your profile <ArrowRight size={17} /></button><button className="ghost-btn" onClick={() => go("discover")}>Explore signals <Compass size={16} /></button></div></div><div className="signal-diagram"><div className="diagram-node"><span>I NEED</span><small>share what matters</small></div><div className="diagram-line"><i /><i /><i /></div><div className="diagram-core"><OfficialLogo small /><span>NIVO</span></div><div className="diagram-line diagram-line--right"><i /><i /><i /></div><div className="diagram-node diagram-node--right"><span>I CAN</span><small>make it useful</small></div></div></section><section id="how" className="landing-how section-shell"><p className="eyebrow">How it works</p><div className="landing-how-grid"><h2>Need → discover →<br /><span>connect → solve.</span></h2><p>Every NIVO interaction begins with a clear signal and leads toward a useful person-to-person connection. No followers, no noisy feed, no false matching claims.</p></div></section></main><footer className="footer section-shell"><div><div className="brand"><OfficialLogo /><span className="brand-name">NIVO</span></div><p>CONNECT WHAT MATTERS</p></div><span className="footer-note">© 2026 NIVO · Everyone needs. Everyone can.</span></footer></div>;
  }

  return <div className="nivo-app app-shell"><header className="topbar"><button className="brand brand-button" onClick={() => go("dashboard")}><OfficialLogo /><span className="brand-name">NIVO</span></button><nav className="desktop-nav app-nav"><button className={screen === "dashboard" ? "active" : ""} onClick={() => go("dashboard")}>Home</button><button className={screen === "discover" ? "active" : ""} onClick={() => go("discover")}>Discover</button><button className={screen === "connections" || screen === "chat" ? "active" : ""} onClick={() => go("connections")}>Connections</button><button className={screen === "profile" ? "active" : ""} onClick={() => go("profile")}>Profile</button></nav><div className="topbar-actions"><button className="primary-btn primary-btn--compact" onClick={() => startComposer("need")}><Plus size={15} /> Create</button><button className="menu-btn" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="mobile-menu"><button onClick={() => go("dashboard")}>Home</button><button onClick={() => go("discover")}>Discover</button><button onClick={() => go("connections")}>Connections</button><button onClick={() => go("profile")}>Profile</button></div>}</header><main className="app-main">
    {screen === "dashboard" && <section className="dashboard section-shell"><div className="dashboard-head"><div><p className="eyebrow">Your NIVO</p><h1>Start with what<br /><span>matters now.</span></h1></div><p>{auth.user?.name ? `Welcome, ${auth.user.name}.` : "Put a need or capability into the network."}</p></div><div className="action-split"><button onClick={() => startComposer("need")}><span className="action-icon"><Search size={22} /></span><div><small>Share an intention</small><strong>+ I NEED</strong><p>Find a person, skill, answer, or opportunity.</p></div><ArrowRight size={18} /></button><button onClick={() => startComposer("can")}><span className="action-icon action-icon--violet"><Zap size={22} /></span><div><small>Share a capability</small><strong>+ I CAN</strong><p>Make your knowledge, work, or help discoverable.</p></div><ArrowRight size={18} /></button></div><div className="app-section-head"><div><p className="eyebrow">Your active signals</p><h2>What you’ve put<br />into the network.</h2></div><button className="text-btn" onClick={() => go("discover")}>Discover people <ArrowRight size={15} /></button></div>{ownSignalsQuery.isLoading ? <div className="loading-row"><Loader2 className="spin" /> Loading your signals</div> : ownSignalsQuery.data?.length ? <div className="signal-list own-signal-list">{ownSignalsQuery.data.map((signal) => <article className="signal-row" key={signal.id}><span className={`type-pill ${signal.type === "can" ? "type-pill--violet" : ""}`}>{signal.type === "need" ? "I NEED" : "I CAN"}</span><div><h3>{signal.title}</h3><p>{signal.description}</p><small>{signal.category} · {signal.language} · {signal.status}</small></div></article>)}</div> : <div className="empty-state"><span className="empty-icon"><Plus size={19} /></span><h3>Your network starts here.</h3><p>You have not posted a NEED or CAN yet. Add one clear signal to make it discoverable.</p><button className="ghost-btn" onClick={() => startComposer("need")}>Post your first need <ArrowRight size={15} /></button></div>}</section>}
    {screen === "discover" && <section className="discover-page section-shell"><div className="app-section-head"><div><p className="eyebrow">Explore the network</p><h1>Find the signal<br /><span>that matters.</span></h1></div><p className="section-intro">Only signals posted by NIVO members appear here. Open a member profile, review the live signal, or send a thoughtful request.</p></div><div className="filter-stack"><div className="filter-group"><span>TYPE</span>{["all", "need", "can"].map((type) => <button key={type} className={typeFilter === type ? "active" : ""} onClick={() => setTypeFilter(type as "all" | SignalMode)}>{type === "all" ? "All signals" : type === "need" ? "I NEED" : "I CAN"}</button>)}</div><div className="category-row">{categories.map((category) => <button className={categoryFilter === category ? "active" : ""} key={category} onClick={() => setCategoryFilter(category)}>{category}</button>)}</div></div>{signalsQuery.isLoading ? <div className="loading-row"><Loader2 className="spin" /> Loading live signals</div> : signalsQuery.isError ? <div className="empty-state"><h3>We could not load signals.</h3><p>Please check your connection and try again.</p><button className="ghost-btn" onClick={() => signalsQuery.refetch()}>Retry</button></div> : signals.length ? <div className="live-signal-grid">{signals.map((signal) => <article className="live-signal-card" key={signal.id}><div className="card-top"><span className={`type-pill ${signal.type === "can" ? "type-pill--violet" : ""}`}>{signal.type === "need" ? "I NEED" : "I CAN"}</span><span className="signal-status">Live</span></div><h3>{signal.title}</h3><p>{signal.description}</p><div className="signal-taxonomy"><span>{signal.category}</span><span>{signal.language}</span>{signal.location && <span>{signal.location}</span>}</div><button className="signal-owner signal-owner--button" onClick={() => go("member", signal.owner.id)}><Avatar name={signal.owner.name} photoUrl={signal.owner.photoUrl} /><div><strong>{signal.owner.name ?? "NIVO member"}</strong><small>{signal.owner.country ?? "Location private"}{signal.owner.phoneVerified ? " · Phone verified" : ""}</small></div><ArrowRight size={14} /></button><div className="card-actions">{signal.owner.id === auth.user?.id ? <button className="muted-btn" onClick={() => go("dashboard")}>Your signal</button> : <button className="primary-btn primary-btn--compact" onClick={() => openConnection(signal.id)}>Connect <Link2 size={15} /></button>}</div></article>)}</div> : <div className="empty-state"><span className="empty-icon"><Compass size={19} /></span><h3>No published signals match these filters yet.</h3><p>Be the first to post a clear NEED or CAN in this space.</p><button className="ghost-btn" onClick={() => startComposer("need")}>Post a need <ArrowRight size={15} /></button></div>}</section>}
    {screen === "member" && <section className="member-page section-shell"><button className="back-btn" onClick={() => go("discover")}><ArrowLeft size={16} /> Discover</button>{memberQuery.isLoading ? <div className="loading-row"><Loader2 className="spin" /> Loading member profile</div> : memberQuery.isError || !memberQuery.data ? <div className="empty-state"><h3>This member profile is not available.</h3><p>It may have been removed or restricted through privacy controls.</p><button className="ghost-btn" onClick={() => go("discover")}>Back to discover</button></div> : <><section className="member-hero"><Avatar name={memberQuery.data.user.name} photoUrl={memberQuery.data.profile?.photoUrl} large /><div><p className="eyebrow">NIVO member</p><h1>{memberQuery.data.user.name ?? "NIVO member"}{memberQuery.data.profile?.phoneVerified ? <ShieldCheck size={19} /> : null}</h1><p>{memberQuery.data.profile?.country ?? "Location private"} · {parseList(memberQuery.data.profile?.languages).join(", ") || "Languages private"}</p></div><div className="member-stat"><strong>{memberQuery.data.completedConnections}</strong><span>Established connections</span></div></section><div className="member-grid"><section className="member-about"><p className="eyebrow">About</p><p>{memberQuery.data.profile?.about || "This member has not added an introduction yet."}</p><div className="member-tags"><div><span>Skills</span>{parseList(memberQuery.data.profile?.skills).length ? parseList(memberQuery.data.profile?.skills).map((skill) => <i key={skill}>{skill}</i>) : <small>Not shared</small>}</div><div><span>Interests</span>{parseList(memberQuery.data.profile?.interests).length ? parseList(memberQuery.data.profile?.interests).map((interest) => <i key={interest}>{interest}</i>) : <small>Not shared</small>}</div></div></section><section><p className="eyebrow">Live signals</p><div className="member-signals">{memberQuery.data.signals.length ? memberQuery.data.signals.map((signal) => <article className="signal-row" key={signal.id}><span className={`type-pill ${signal.type === "can" ? "type-pill--violet" : ""}`}>{signal.type === "need" ? "I NEED" : "I CAN"}</span><div><h3>{signal.title}</h3><p>{signal.description}</p><small>{signal.category} · {signal.language}</small></div></article>) : <div className="member-empty">No active signals at this time.</div>}</div></section></div></>}</section>}
    {screen === "connections" && <section className="connections-page section-shell"><div className="app-section-head"><div><p className="eyebrow">Private connections</p><h1>Useful people,<br /><span>real conversations.</span></h1></div><p className="section-intro">Requests are private. Messaging only opens when both people agree to connect.</p></div>{connectionsQuery.isLoading ? <div className="loading-row"><Loader2 className="spin" /> Loading connections</div> : connections.length ? <div className="connection-list">{connections.map((connection) => { const incoming = connection.recipientId === auth.user?.id; const person = connection.counterpart; return <article className="connection-card" key={connection.id}><button className="connection-avatar-button" onClick={() => person && go("member", person.id)}><Avatar name={person?.name} photoUrl={person?.photoUrl} large /></button><div className="connection-content"><div className="connection-title"><div><span className={`connection-status connection-status--${connection.status}`}>{connection.status}</span><button className="member-name-button" onClick={() => person && go("member", person.id)}><h3>{person?.name ?? "NIVO member"}{person?.phoneVerified && <ShieldCheck size={14} />}</h3></button><p>{connection.note}</p></div>{connection.status === "accepted" && <button className="primary-btn primary-btn--compact" onClick={() => go("chat", connection.id)}>Message <MessageCircle size={15} /></button>}</div><small>{incoming ? "They want to connect with you" : "Your connection request"}</small>{connection.status === "pending" && <div className="connection-actions">{incoming ? <><button className="primary-btn primary-btn--compact" disabled={acceptConnection.isPending} onClick={() => acceptConnection.mutate({ id: connection.id })}>Accept <Check size={15} /></button><button className="muted-btn" disabled={declineConnection.isPending} onClick={() => declineConnection.mutate({ id: connection.id })}>Decline</button></> : <button className="muted-btn" disabled={cancelConnection.isPending} onClick={() => cancelConnection.mutate({ id: connection.id })}>Cancel request</button>}</div>}</div></article>; })}</div> : <div className="empty-state"><span className="empty-icon"><Link2 size={19} /></span><h3>No connections yet.</h3><p>Discover a posted signal and send a thoughtful request to start a conversation.</p><button className="ghost-btn" onClick={() => go("discover")}>Explore signals <ArrowRight size={15} /></button></div>}</section>}
    {screen === "chat" && <section className="chat-page section-shell"><button className="back-btn" onClick={() => go("connections")}><ArrowLeft size={16} /> Connections</button>{selectedConnection ? <div className="chat-shell"><header className="chat-head"><button className="connection-avatar-button" onClick={() => selectedConnection.counterpart && go("member", selectedConnection.counterpart.id)}><Avatar name={selectedConnection.counterpart?.name} photoUrl={selectedConnection.counterpart?.photoUrl} /></button><div><h2>{selectedConnection.counterpart?.name ?? "NIVO member"}</h2><span><span className="online-dot" /> Connection established</span></div><button className="muted-btn" onClick={() => { if (window.confirm("Block this member? This will hide their signals and connections from your account.")) blockUser.mutate({ userId: selectedConnection.counterpart!.id }); }}><ShieldAlert size={15} /> Block</button></header><div className="message-thread">{messagesQuery.isLoading ? <div className="loading-row"><Loader2 className="spin" /> Loading messages</div> : messagesQuery.data?.length ? messagesQuery.data.map((message) => <div key={message.id} className={`message-bubble ${message.senderId === auth.user?.id ? "message-bubble--mine" : ""}`}><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString()}</small></div>) : <div className="chat-empty"><MessageCircle size={22} /><h3>The conversation is ready.</h3><p>Say hello and keep the conversation focused on the connection you both accepted.</p></div>}</div><form className="message-form" onSubmit={submitMessage}><textarea value={messageBody} onChange={(event) => setMessageBody(event.target.value)} placeholder="Write a message…" rows={2} maxLength={4000} /><button className="primary-btn" type="submit" disabled={sendMessage.isPending || !messageBody.trim()}>{sendMessage.isPending ? <Loader2 className="spin" size={17} /> : <Send size={17} />}</button></form></div> : <div className="empty-state"><h3>Choose a connection to open a conversation.</h3><button className="ghost-btn" onClick={() => go("connections")}>Back to connections</button></div>}</section>}
    {screen === "profile" && <section className="profile-page section-shell"><div className="app-section-head"><div><p className="eyebrow">Your profile</p><h1>Let the right person<br /><span>understand you.</span></h1></div>{profileQuery.data?.profile?.phoneVerified ? <span className="verified-pill"><ShieldCheck size={14} /> Phone verified</span> : <span className="unverified-pill">Phone verification not yet connected</span>}</div><form className="profile-form" onSubmit={submitProfile}><section className="profile-preview"><Avatar name={profileQuery.data?.user?.name ?? auth.user?.name} photoUrl={profileForm.photoUrl || null} large /><div><h2>{profileQuery.data?.user?.name ?? auth.user?.name ?? "NIVO member"}</h2><p>{profileForm.country || "Location not shared"}</p><span>{profileForm.languages || "Languages not added"}</span></div></section><div className="form-grid"><InputLabel label="Country"><input value={profileForm.country} onChange={(event) => setProfileForm({ ...profileForm, country: event.target.value })} placeholder="e.g. Kenya" maxLength={100} /></InputLabel><InputLabel label="Profile photo URL"><input type="url" value={profileForm.photoUrl} onChange={(event) => setProfileForm({ ...profileForm, photoUrl: event.target.value })} placeholder="https://…" maxLength={1024} /></InputLabel><InputLabel label="Languages (separate with commas)"><input value={profileForm.languages} onChange={(event) => setProfileForm({ ...profileForm, languages: event.target.value })} placeholder="English, Arabic" /></InputLabel><InputLabel label="Skills (separate with commas)"><input value={profileForm.skills} onChange={(event) => setProfileForm({ ...profileForm, skills: event.target.value })} placeholder="Product design, Flutter" /></InputLabel><InputLabel label="Interests (separate with commas)"><input value={profileForm.interests} onChange={(event) => setProfileForm({ ...profileForm, interests: event.target.value })} placeholder="Learning, collaboration" /></InputLabel><InputLabel label="About"><textarea value={profileForm.about} onChange={(event) => setProfileForm({ ...profileForm, about: event.target.value })} placeholder="Write a short, helpful introduction." rows={5} maxLength={700} /></InputLabel></div><div className="profile-save"><p>Keep personal contact details private. NIVO only shares them if you choose to after a connection.</p><button className="primary-btn" type="submit" disabled={saveProfile.isPending}>{saveProfile.isPending ? <Loader2 className="spin" size={16} /> : <Pencil size={16} />} Save profile</button></div></form><button className="logout-row" onClick={() => auth.logout().then(() => go("landing"))}><LogOut size={15} /> Log out</button></section>}
  </main><nav className="bottom-nav"><button className={screen === "dashboard" ? "active" : ""} onClick={() => go("dashboard")}><HomeIcon size={19} /><span>Home</span></button><button className={screen === "discover" ? "active" : ""} onClick={() => go("discover")}><Compass size={19} /><span>Discover</span></button><button className="create-nav" aria-label="Create a signal" onClick={() => startComposer("need")}><Plus size={23} /></button><button className={screen === "connections" || screen === "chat" ? "active" : ""} onClick={() => go("connections")}><MessageCircle size={19} /><span>Connections</span></button><button className={screen === "profile" ? "active" : ""} onClick={() => go("profile")}><UserRound size={19} /><span>Profile</span></button></nav>
  {composerMode && <div className="modal-backdrop"><form className="request-modal composer-modal" onSubmit={submitSignal}><button type="button" className="modal-close" onClick={() => setComposerMode(null)}><X size={18} /></button><p className="eyebrow">Publish a signal</p><h2>{composerMode === "need" ? "What do you need?" : "What can you provide?"}</h2><p className="modal-copy">Use clear language so the right person can understand the signal quickly.</p><InputLabel label="Short title"><input value={signalForm.title} onChange={(event) => setSignalForm({ ...signalForm, title: event.target.value })} placeholder={composerMode === "need" ? "I need a website for my business" : "I can teach conversational English"} minLength={5} maxLength={180} required /></InputLabel><InputLabel label="Details"><textarea value={signalForm.description} onChange={(event) => setSignalForm({ ...signalForm, description: event.target.value })} placeholder="Add useful detail about the need or capability." rows={4} minLength={12} maxLength={2400} required /></InputLabel><div className="compact-form-grid"><InputLabel label="Category"><select value={signalForm.category} onChange={(event) => setSignalForm({ ...signalForm, category: event.target.value })}>{categories.slice(1).map((category) => <option key={category} value={category}>{category}</option>)}</select></InputLabel><InputLabel label="Language"><input value={signalForm.language} onChange={(event) => setSignalForm({ ...signalForm, language: event.target.value })} maxLength={64} required /></InputLabel></div><InputLabel label="Location (optional)"><input value={signalForm.location} onChange={(event) => setSignalForm({ ...signalForm, location: event.target.value })} placeholder="e.g. Remote, Nairobi" maxLength={120} /></InputLabel><button className="primary-btn primary-btn--wide" type="submit" disabled={createSignal.isPending}>{createSignal.isPending ? <Loader2 className="spin" size={16} /> : "Publish signal"}<ArrowRight size={16} /></button></form></div>}
  {selectedSignal && <div className="modal-backdrop"><form className="request-modal" onSubmit={submitConnection}><button type="button" className="modal-close" onClick={() => setRequestSignalId(null)}><X size={18} /></button><p className="eyebrow">Connection request</p><h2>Make the first move.</h2><p className="modal-copy">Tell {selectedSignal.owner.name ?? "this member"} why you want to connect. This message is only visible to them.</p><div className="request-person"><Avatar name={selectedSignal.owner.name} photoUrl={selectedSignal.owner.photoUrl} large /><div><strong>{selectedSignal.owner.name ?? "NIVO member"}</strong><span>{selectedSignal.category} · {selectedSignal.owner.country ?? "Location private"}</span></div></div><InputLabel label="Your note"><textarea value={requestNote} onChange={(event) => setRequestNote(event.target.value)} rows={4} minLength={10} maxLength={1200} required /></InputLabel><button className="primary-btn primary-btn--wide" type="submit" disabled={requestConnection.isPending}>{requestConnection.isPending ? <Loader2 className="spin" size={16} /> : "Send connection request"}<ArrowRight size={16} /></button><div className="trust-row"><button type="button" onClick={() => { if (window.confirm("Report this member for review?")) reportUser.mutate({ reportedUserId: selectedSignal.owner.id, reason: "other", details: null }); }}><Flag size={14} /> Report</button><button type="button" onClick={() => { if (window.confirm("Block this member? You will no longer see their signals or connections.")) blockUser.mutate({ userId: selectedSignal.owner.id }); }}><ShieldAlert size={14} /> Block</button></div></form></div>}
  </div>;
}
