// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kinba-mobile/KINBAFeed.tsx": () => import("../components/mockups/kinba-mobile/KINBAFeed.tsx"),
  "./components/mockups/templates/DiscoBirthdayPartyPoster-Fus4ei/BirthdayCollage.tsx": () => import("../components/mockups/templates/DiscoBirthdayPartyPoster-Fus4ei/BirthdayCollage.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-Ei8SO6/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-Ei8SO6/DinnerPartyPosterSeverance.tsx")
};
