// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kinba-mobile/KINBAFeed.tsx": () => import("../components/mockups/kinba-mobile/KINBAFeed.tsx")
};
